// CIPHER SCORE — Cairo Contracts
// Starknet Re{define} Hackathon 2026
//
// Module declarations for scarb build

// Main oracle contract
mod income_oracle;

// ZK verifier — generated by Garaga after circuit compilation
// Uncomment this line after running: ./scripts/compile_circuit.sh
// mod income_verifier;
